# Generated by Django 3.0.3 on 2020-02-26 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200226_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +7 9999999', regex='^7?\\d{10}$')]),
        ),
    ]
