# Generated by Django 3.0.3 on 2020-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200504_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
