# Generated by Django 3.0.3 on 2020-05-05 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200504_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8591b661-b9aa-4e60-a179-a0e66d2a6e4d'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='deathstar.jpg', upload_to='images/%Y/%m/%d'),
        ),
    ]
